[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20.12.2"
  NEXT_PUBLIC_BASE_PATH = "/"

[[plugins]]
  package = "@netlify/plugin-nextjs"
